#
# User configuration sourced by interactive shells
#
# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

# Change default zim location
# Start zim

setxkbmap -layout us,de -option grp:menu_toggle -option caps:swapescape
source $HOME/.aliases
source /usr/share/vim/vimfiles/gruvbox_256palette.sh
export VISUAL=vim
export EDITOR="$VISUAL"
export PATH=$PATH:/opt/pymol
alias sus='i3lock && systemctl suspend'
alias sm='snakemake'
alias dotdrop='$HOME/.dotfiles/dotdrop.sh --cfg=$HOME/.dotfiles/config.yaml'
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
source /opt/gromacs-2019/bin/GMXRC
source ~/programs/plumed2/sourceme.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/roetzscher/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/roetzscher/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/roetzscher/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/roetzscher/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

